apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet291024tektongithub
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet291024tektongithub 
  name: dotnet291024tektongithub
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet291024tektongithub 
