apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dotnet291024tektongithub
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-jsmid:32b04779ea6bb6edda8eb339e9e71619fb39975d@sha256:e4dd3a998c0dfa2b18ac5c055e93664b72d63eee750d92d30705f5aca3c65d95
          name: container-image
